[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["fs", "test-util", "macros"] }
oas = "0.2.1"
serde_json = "1.0.145"
serde_yaml = "0.9"
