[package]
name = "rust-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
codegen = { path = "../../codegen" }
ir = { path = "../../ir" }
askama = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
